import type { Metadata } from "next";
import { Cairo, Space_Grotesk, JetBrains_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { LocaleProvider } from "@/components/LocaleProvider";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { JAM_CONFIG } from "@/lib/jam-config";
import { formatEnglishDateRange } from "@/lib/date-format";
import { LOCALE_COOKIE, DEFAULT_LOCALE, dir, type Locale } from "@/lib/i18n";

const arabic = Cairo({
  variable: "--font-arabic",
  subsets: ["arabic", "latin"],
  weight: ["400", "600", "700", "900"],
});

const display = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const mono = JetBrains_Mono({
  variable: "--font-mono-display",
  subsets: ["latin"],
  weight: ["400", "700"],
});

// Absolute base for og:image and friends. Social scrapers won't resolve relative
// URLs, so without metadataBase a shared link renders with no card at all.
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") || "https://www.gamezanga.net";

const SITE_TITLE = `${JAM_CONFIG.name_ar} ${JAM_CONFIG.edition} — ${JAM_CONFIG.name_en}`;

// "13–16 August 2026". formatEnglishDateRange() spells both ends out in full,
// which reads fine in the hero but is clumsy in a share card, so collapse the
// month and year when the range sits inside one month.
function compactRange(startISO: string, endISO: string): string {
  const opts = { timeZone: "Asia/Riyadh" } as const;
  const start = new Date(startISO);
  const end = new Date(endISO);
  const day = (d: Date) => new Intl.DateTimeFormat("en", { ...opts, day: "numeric" }).format(d);
  const monthYear = (d: Date) =>
    new Intl.DateTimeFormat("en", { ...opts, month: "long", year: "numeric" }).format(d);
  return monthYear(start) === monthYear(end)
    ? `${day(start)}–${day(end)} ${monthYear(start)}`
    : formatEnglishDateRange(startISO, endISO);
}

// Derived from jam-config so the shared card can't drift from the actual dates.
const SOCIAL_DESCRIPTION =
  `فعالية عربية لتطوير الألعاب على مدى ٧٢ ساعة · A 72-hour Arabic-language game jam. ` +
  `Edition ${JAM_CONFIG.edition} — ${compactRange(JAM_CONFIG.jam_start, JAM_CONFIG.jam_end)}.`;

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: SITE_TITLE,
  description: `${JAM_CONFIG.tagline_ar} — ${JAM_CONFIG.tagline_en}`,
  // Icons come from the app/ file conventions (icon.png, apple-icon.png,
  // favicon.ico) — an explicit `icons` entry here would suppress them.
  // public/og.png is regenerated by scripts/build-og-image.py when the edition
  // number or the jam dates change.
  openGraph: {
    type: "website",
    siteName: JAM_CONFIG.name_en,
    locale: "ar_AR",
    alternateLocale: "en_US",
    url: SITE_URL,
    title: SITE_TITLE,
    description: SOCIAL_DESCRIPTION,
    images: [{
      url: "/og.png",
      width: 1200,
      height: 630,
      alt: `${JAM_CONFIG.name_ar} — ${JAM_CONFIG.name_en}`,
    }],
  },
  twitter: {
    card: "summary_large_image",
    site: "@GameZanga",
    creator: "@GameZanga",
    title: SITE_TITLE,
    description: SOCIAL_DESCRIPTION,
    images: ["/og.png"],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const stored = cookieStore.get(LOCALE_COOKIE)?.value;
  const locale: Locale = stored === "en" || stored === "ar" ? stored : DEFAULT_LOCALE;

  return (
    <html
      lang={locale}
      dir={dir(locale)}
      className={`${arabic.variable} ${display.variable} ${mono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LocaleProvider initialLocale={locale}>
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
        </LocaleProvider>
      </body>
    </html>
  );
}
